### ISSUE TITLE
Null-Safety?

### ISSUE THREAD

**Issue by d9media** [godlessturtle/flutter_floating_bottom_navigation_bar#11]
Hi and Thank you for the work on this package!

I was running flutter outdated --mode=null-safety to check which packages need upgrading to be compatible with null-safety and the command came back negative with flutter_floating_bottom_navigation_bar.

Admittedly, I haven't really looked into the whole null-safety story much yet but are you aware of it and is the package compatible? Once I get a clear picture I can help out and port the code over. Just wondering whether this is something you had already looked into.

Cheers!

**Comment by rgbinnovation** [comment]
I would like this package updated to null-safety as well, please.

**Comment by right7ctrl** [comment]
Merged, thanks to @ajomuch92
