### ISSUE TITLE
Getting a white thick margin around the FloatingNavBar

### ISSUE THREAD

**Issue by mishrhm** [godlessturtle/flutter_floating_bottom_navigation_bar#2]
I have already set the extendBody : true but still I cant see the body but  some kind of thick white margin is around the FloatingNavBar. Can you please help?
![Screenshot_1590866449](https://user-images.githubusercontent.com/36451871/83337430-cd58b580-a2d8-11ea-9500-8d5482a56b1a.png)

**Comment by mishrhm** [comment]
I actually got rid of this by setting resizeToAvoidBottomInset : false
but still curious to know Why extendBody wasnt enough?

**Comment by right7ctrl** [comment]
Thank you for pointing out that, i'll edit readme

**Comment by mjarpitanand** [comment]
Hi friends,

i am not able to solve this even by applying @mishrhm solution. Getting a thick margin.
