### ISSUE TITLE
[Feature] Custom Item Container

### ISSUE THREAD

**Issue by stefensuhat** [godlessturtle/flutter_floating_bottom_navigation_bar#4]
Enabled this so can make like Pinterest floating navbar, but with box shadow / border instead of just plain white. 

![](https://newsroom.pinterest.com/sites/default/files/inline-images/Board_EN-US%20%281%29.png)

Thanks!

**Comment by stefensuhat** [comment]
my bad. you have item builder to make this happen.

**Comment by Peerpal** [comment]
i just made a pull request with a fix. hopefully it gets merged
