### ISSUE TITLE
Can't use FontAwesomeIcon in icon properties?

### ISSUE THREAD

**Issue by ruslanou** [godlessturtle/flutter_floating_bottom_navigation_bar#7]
Hello, Thanks for the this great package. Unfortunately when i'm using FontAwesomeIcon in icon property. It showed like japan alfabet. How to solved it?

**Comment by right7ctrl** [comment]
i think, its not about this package, may be you forgot to restart app after install the fontawesome package? Please let me know if its still a problem.

**Comment by ruslanou** [comment]
You're  right. i forgot to restart the app
